### ISSUE TITLE
Can't add Capacitors from Thermal Expansion

### ISSUE THREAD

**Issue by Decrepitdoors** [oitsjustjose/TiCon-Addons#10]
Would this be possible to add? Tinkers seems to have taken out the option and I want my RF tools back!

**Comment by oitsjustjose** [comment]
I had originally thought about it, but since the days of the 1.7.10 RF API, much has changed:

Nobody knows what they want anymore. Do they want RF tools? Tesla tools? ForgeEnergy tools? Opinions seem all over the place, and the most common practice has been to adopt all three. If I had more time, maybe I'd try to learn 3 new APIs and also figure out a way to hack them into items that aren't actually mine (specifically: the files for Tinkers' Construct tools aren't mine and aren't modifiable, thus I have to come up with other ways of implementing the ability to consume power instead of durability).

I'll.... eventually give it a thought, but it's highly unlikely. Closing for now - you'll know if I decide to consider it, as I'll reopen it :)

**Comment by BrainStone** [comment]
Would love to see this again, too!

**Comment by Pival81** [comment]
So... Is it a definitive no?
