### ISSUE TITLE
No Recipe for Moss Ball - 1.10.2

### ISSUE THREAD

**Issue by Utildayael** [oitsjustjose/TiCon-Addons#6]
Maybe I'm missing something but I see no recipe for a moss ball to do auto repair!

Only items JEI reports are AMELIORATION_KIT and the three upgrade items.

I searched for moss, mossy and notta. Don't see it in creative either. Tried the moss stone recipe and nothing.

Help :)

**Comment by oitsjustjose** [comment]
From the CurseForge and GitHub changelog:

> 1.0.3:
-Changed: Auto-Repair is now Amelioration (a synonym for "improving"). The mechanics work the same, but recipe has changed
-Changed: Textures for all items + proper 1.9.x+ model support
-Changed: "Officially" supporting 1.10.x+, but also works on 1.9.4 :)
-Removed: Moss Ball in place for the Amelioration Kit. 
-NOTE: Working on a JEI plugin. Until then, to craft the Amelioration Kit with default recipe, do such:

> [M] [M] [M]
[M] [E] [M]
[M] [M] [M]

> Where [M] is Moss Stone, and E is an enchanted book or item with Mending on it

I made these changes because Boni has his own implementation of auto repair in the works, but it's more like vanilla mending. If you don't like the mending recipe I've made there's a config option for that.

**Comment by Utildayael** [comment]
Apologies! I had looked at the Curse page and comments but totally spaced the changelog! Derp. :)

Thank you sir for the quick reply. :)

**Comment by oitsjustjose** [comment]
Absolutely!! I hope these changes don't make the mod less valuable, it's just kinda tough to work around when the main mod itself adds something you were adding with the same name and textures, but different mechanics.... So I had to compromise but also rebalance a little. But config options and CraftTweaker exist for a reason!

**Comment by Utildayael** [comment]
:)

It's much needed sir! You do the TIC community a great service.
