### ISSUE TITLE
Addons I would appreciate.

### ISSUE THREAD

**Issue by mightydanp** [oitsjustjose/TiCon-Addons#7]
I was wondering if you can add a few things to tinkers construct.
    -Change block mining level.
    -Change tool material mining level.
i would appreciate this.

**Comment by oitsjustjose** [comment]
I don't think I'll be adding either one of these, as they aren't within a logical realm of this mod. Tinkers' itself adds a way to upgrade the harvesting level of a tool. What do you mean by "block mining level"? Do you mean take a block (ex: obsidian) and change it from requiring diamond to requiring iron or stone?

Tinkers' Addons is actually coming to a close, because Tinkers' Construct's vanilla methods, as well as [Tinkers' Tool Leveling](https://minecraft.curseforge.com/projects/tinkers-tool-leveling) pretty  much do everything and more than Tinkers' Addons does.

You can get extra modifiers from TiC Tool Leveling, and vanilla TiC has its own method of auto-reparation now.

**Comment by mightydanp** [comment]
Why not try to add more modifiers or material support to tinkers instead of closing the mod. It is called tinkere addon
